name: 🎤 Tech Talk Request
description: Request a new technical deep-dive presentation
title: "[Tech Talk] "
labels: ["tech-talk", "tech-talk:intake"]

body:
  - type: markdown
    attributes:
      value: |
        ## 🎤 Tech Talk Pipeline

        Submitting this issue kicks off an automated 4-phase workflow:

        | Phase | What Happens | Your Action |
        |-------|-------------|-------------|
        | **1. Research** | Copilot CLI researches URLs & web, downloads images | None — automatic |
        | **2. Plan** | Copilot CLI creates a content plan from research | None — automatic |
        | **3. Build** | Copilot CLI generates the full README | Comment `/approve-plan` after reviewing |
        | **4. Slides** | Copilot CLI generates Slidev slides | Add `tech-talk:slides` label |

        You'll get status updates as comments on this issue throughout the process.

  - type: input
    id: topic
    attributes:
      label: Tech Talk Topic
      description: Short name used for the directory (e.g., copilot-memory, agent-teams)
      placeholder: "copilot-memory"
    validations:
      required: true

  - type: textarea
    id: source_urls
    attributes:
      label: Source URLs
      description: Documentation, blog posts, or repos to research (one per line)
      placeholder: |
        https://docs.github.com/copilot/...
        https://github.blog/...
    validations:
      required: true

  - type: input
    id: primary_question
    attributes:
      label: Primary Question
      description: The ONE question this tech talk should answer
      placeholder: "e.g., How do I get Copilot assistance without leaving the terminal?"
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      options:
        - Developers
        - Architects
        - DevOps Engineers
        - Technical Leaders
        - Mixed Audience
    validations:
      required: true

  - type: dropdown
    id: section
    attributes:
      label: Index Section
      description: Which section of the slide index should this talk appear in?
      options:
        - "Copilot Surfaces"
        - "Context & Customization"
        - "Agent Architecture"
        - "Agentic Transformation"
    validations:
      required: true

  - type: dropdown
    id: duration
    attributes:
      label: Expected Duration
      options:
        - "30 minutes"
        - "45 minutes"
        - "60 minutes"
      default: 0
    validations:
      required: true

  - type: textarea
    id: guidance
    attributes:
      label: Guidance (optional)
      description: Any specific focus areas, capabilities to cover, or constraints?
      placeholder: "e.g., Focus on enterprise scenarios, must include architecture diagrams"
